version: '3'

services:
  kali:
    build: 
      context: ./kali
    volumes:
      - ./kali/kali-files:/root
    network_mode: host
    command: /bin/bash -c "trap 'exit 0' INT; while true; do sleep 1; done"

  target:
    build: 
      context: ./target
    volumes:
      - ./target/target-files:/root
    networks:
      - pentest-network

networks:
  pentest-network:
    driver: bridge
